name             'custom_apache'
issues_url       'https://problems.com'
source_url       'https://source.com'
maintainer       'Admin'
maintainer_email 'admin@example.com'
license          'Apache-2.0'
description      'Installs/Configures custom_apache'
long_description 'Installs/Configures custom_apache'
version          '0.1.0'
chef_version     '14.0'
supports         'ubuntu'
